name: herehear
description: here N hear

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  get: ^4.1.4
  comment_box: ^0.0.16
  google_sign_in: ^4.5.9
  permission_handler: ^8.1.2
  agora_rtc_engine: ^4.0.1
  diffutil_dart: ^2.0.0+1
  equatable: ^2.0.3
  flutter_chat_types: ^2.2.0
  flutter_link_previewer: ^2.1.0
  intl: ^0.17.0
  meta: ^1.3.0
  photo_view: ^0.11.1
  file_picker: ^3.0.2+2
  flutter_chat_ui: ^1.1.5
  image_picker: ^0.8.0+3
  mime: ^1.0.0
  open_file: ^3.2.1
  uuid: ^3.0.4
  geolocator: ^7.2.0+1
  geocoder: ^0.2.1
  firebase_auth: ^2.0.0
  firebase_storage: ^9.0.0
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_screenutil: ^5.0.0+2
  smart_select: ^4.3.2
  flutter_pagewise: ^2.0.1
  sms_autofill: ^2.0.0
  badges: ^2.0.1
  flutter_local_notifications: ^6.1.0
  firebase_messaging: ^10.0.4
  overlay_support: ^1.2.1
  flutter_firebase_chat_core: ^1.1.1
  search_widget: ^1.0.2
  cloud_functions: ^3.0.0
  provider: ^5.0.0
  logger: ^1.0.0
  flutter_tags: ^0.4.9+1
  record: ^3.0.0
  just_audio: ^0.8.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_tts: ^3.2.2
  flutter_statusbarcolor: ^0.2.3
  fluttertoast: ^8.0.8
  wave: ^0.2.0
  keyboard_actions: "^3.3.1+1"
  flutter_native_splash: ^1.2.1
#  multiple_stream_builder: ^2.0.0

  #  just_audio: ^0.9.2








#  audioplayers: ^0.18.2
#  assets_audio_player: ^3.0.2
#  just_audio: ^0.9.2




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/login/google.png
    - assets/suhyun.jpg
    - assets/gyeongsu.jpg
    - assets/images/me.jpg
    - assets/images/you.png
    - assets/images/he.jpg
    - assets/images/she.jpg
    - assets/images/it.jpg
    - assets/images/you2.jpg
    - assets/images/it2.jpg
    - assets/images/she2.jpeg
    - assets/images/group.png
    - assets/images/sing.png
    - assets/images/voiceCopy.png
    - assets/images/mike.png
    - assets/images/mike2.png
    - assets/messages.json
    - assets/messages2.json
    - assets/icons/home_stroke.png
    - assets/icons/home_active.png
    - assets/icons/favorite_stroke.png
    - assets/icons/favorite_active.png
    - assets/icons/people_stroke.png
    - assets/icons/people_active.png
    - assets/icons/people_black.png
    - assets/icons/search_stroke.png
    - assets/icons/search_active.png
    - assets/icons/profile_stroke.png
    - assets/icons/profile_active.png
    - assets/icons/profile_black.png
    - assets/icons/add.png
    - assets/icons/search.png
    - assets/icons/search2.png
    - assets/icons/addButton_blue.png
    - assets/icons/notification.png
    - assets/icons/crown_gold.png
    - assets/icons/crown_silver.png
    - assets/icons/crown_bronze.png
    - assets/icons/exit.png
    - assets/icons/mic_fill.png
    - assets/icons/mic_fill2.png
    - assets/icons/mic_off.png
    - assets/icons/report.png
    - assets/icons/report_red.png
    - assets/icons/groupBlack.png
    - assets/icons/groupWhite.png
    - assets/icons/location.png
    - assets/icons/leaf.png
    - assets/icons/leaf2.png
    - assets/icons/bell.png
    - assets/icons/bell_white.png
    - assets/icons/playButton.png
    - assets/icons/playButton_grey.png
    - assets/icons/goOut_red.png
    - assets/icons/hand.png
    - assets/icons/more.png
    - assets/icons/more_white.png
    - assets/icons/live.png
    - assets/icons/history.png
    - assets/icons/reload.png
    - assets/icons/tree.png
    - assets/icons/smile.png
    - assets/icons/healing.png
    - assets/icons/talk.png
    - assets/icons/eyes.png
    - assets/icons/book.png
    - assets/icons/music.png
    - assets/icons/sale.png
    - assets/icons/advertise.png
    - assets/icons/pen.png
    - assets/icons/bigEye.png
    - assets/icons/eye-off.png
    - assets/icons/heart.png
    - assets/icons/heart_grey.png
    - assets/icons/heart_white.png
    - assets/icons/heart_fill.png
    - assets/icons/heart_blue.png
    - assets/icons/heart_stroke_blue.png
    - assets/icons/chat.png
    - assets/icons/chat_grey.png
    - assets/icons/chat_black.png
    - assets/icons/more_grey.png
    - assets/icons/line_short.png
    - assets/icons/record.png
    - assets/icons/lock_white.png
    - assets/icons/lock_grey.png
    - assets/icons/unlock_white.png
    - assets/icons/unlock_grey.png
    - assets/icons/clock_black.png
    - assets/icons/clock_white.png
    - assets/icons/clock_grey.png
    - assets/icons/pause_white.png
    - assets/icons/stop_white.png
    - assets/icons/play_white.png
    - assets/icons/friends.png
    - assets/icons/addFriend.png
    - assets/icons/play.png
    - assets/icons/kakao.png
    - assets/icons/naver.png
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/icons/apple.png
    - assets/icons/trashbox.png
    - assets/icons/record_white.png
    - assets/icons/upload.png
    - assets/icons/camera.png
    - assets/icons/camera_blue.png
    - assets/icons/gallery.png
    - assets/icons/call.png
    - assets/icons/expand_grey.png
    - assets/icons/expand_black.png
    - assets/icons/micButton.png
    - assets/icons/micButton_mute.png
    - assets/icons/pause.png
    - assets/icons/notice.png
    - assets/icons/reload_blue.png
    - assets/icons/edit.png
    - assets/icons/mic_fill_black.png
    - assets/icons/mic-off.png
    - assets/images/game.png
    - assets/images/IU.png
    - assets/images/rive_red.png
    - assets/images/gamer.png
    - assets/images/sora.jpg
    - assets/images/mountain.jpg
    - assets/images/mic1.jpg
    - assets/images/mic2.jpg
    - assets/images/moon.jpg
    - assets/images/cat.jpg
    - assets/images/dog.jpg
    - assets/images/hamster.jpg
    - assets/images/HGU.jpg
    - assets/images/logo.png
    - assets/images/goldCrown.png
    - assets/images/silverCrown.png
    - assets/images/bronzeCrown.png
    - assets/images/playButton.png
    - assets/images/playButton2.png
    - assets/images/playButton3.png
    - assets/images/stopButton.png
    - assets/images/sample1.jpg
    - assets/images/sample2.jpg
    - assets/images/sample3.jpg
    - assets/images/sample4.jpg
    - assets/images/liveImage.png
    - assets/images/streamer.png
    - assets/audio/girlVoice.mp3
    - assets/audio/vj.mp3
    - assets/audio/loveRain.mp3
    - assets/audio/yuan.mp3
    - assets/audio/politician.mp3
    - assets/images/testUser.png
    - assets/audio/broadcast/sea.mp3
    - assets/audio/broadcast/piano.mp3
    - assets/images/broadcast/sea.jpg
    - assets/images/broadcast/piano.png
    - assets/images/broadcast/bread.jpg
    - assets/images/broadcast/asmr.jpg
    - assets/images/broadcast/food.jpg
    - assets/images/broadcast/gs.png
    - assets/images/broadcast/talk.jpg
    - assets/images/groupcall/apart.jpg
    - assets/images/groupcall/black.jpg
    - assets/images/groupcall/church.jpg
    - assets/images/groupcall/drama.jpg
    - assets/images/groupcall/english.jpg
    - assets/images/groupcall/talk.jpg
    - assets/images/groupcall/voice.jpg
    - assets/images/groupcall/fish.jpg
    - assets/images/broadcast/rosegold.jpg
    - assets/images/mainLogo.png
    - assets/logo/logo-round.png
    - assets/logo/logo-square.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Baloo Bhai
      fonts:
        - asset: fonts/BalooBhai-Regular.ttf
    - family: Noto Sans CJK kr-bold
      fonts:
        - asset: fonts/NotoSansCJKkr-Bold.ttf
    - family: Noto Sans CJK kr-medium
      fonts:
        - asset: fonts/NotoSansCJKkr-Medium.ttf
    - family: Noto Sans CJK kr-regular
      fonts:
        - asset: fonts/NotoSansCJKkr-Regular.ttf
    - family: Noto Sans-extraLight
      fonts:
          - asset: fonts/NotoSans-ExtraLight.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter_native_splash:
  image: assets/images/mainLogo.png
  color: "42a5f5"