name: herehear
description: here N hear

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  get: ^4.1.4
  comment_box: ^0.0.16
  google_sign_in: ^4.5.9
  permission_handler: ^8.1.2
  agora_rtc_engine: ^3.3.3
  diffutil_dart: ^2.0.0+1
  equatable: ^2.0.3
  flutter_chat_types: ^2.2.0
  flutter_link_previewer: ^2.1.0
  intl: ^0.17.0
  meta: ^1.3.0
  photo_view: ^0.11.1
  file_picker: ^3.0.2+2
  flutter_chat_ui: ^1.1.5
  image_picker: ^0.8.0+3
  mime: ^1.0.0
  open_file: ^3.2.1
  uuid: ^3.0.4
  geolocator: ^7.2.0+1
  geocoder: ^0.2.1
  firebase_auth: ^2.0.0
  firebase_storage: ^9.0.0
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_screenutil: ^5.0.0+2
  smart_select: ^4.3.2
  flutter_pagewise: ^2.0.1
  sms_autofill: ^2.0.0
  badges: ^2.0.1
  just_audio: ^0.9.2
  flutter_local_notifications: ^6.1.0
  firebase_messaging: ^10.0.4
  overlay_support: ^1.2.1







#  audioplayers: ^0.18.2
#  assets_audio_player: ^3.0.2
#  just_audio: ^0.9.2




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/login/google.png
    - assets/suhyun.jpg
    - assets/gyeongsu.jpg
    - assets/images/me.jpg
    - assets/images/you.png
    - assets/images/he.jpg
    - assets/images/she.jpg
    - assets/images/it.jpg
    - assets/images/you2.jpg
    - assets/images/it2.jpg
    - assets/images/she2.jpeg
    - assets/messages.json
    - assets/messages2.json
    - assets/icons/home_stroke.png
    - assets/icons/home_active.png
    - assets/icons/favorite_stroke.png
    - assets/icons/favorite_active.png
    - assets/icons/search_stroke.png
    - assets/icons/search_active.png
    - assets/icons/profile_stroke.png
    - assets/icons/profile_active.png
    - assets/icons/search.png
    - assets/icons/notification.png
    - assets/icons/exit.png
    - assets/icons/mic_fill.png
    - assets/icons/groupBlack.png
    - assets/icons/groupWhite.png
    - assets/images/mountain.jpg
    - assets/images/mic1.jpg
    - assets/images/mic2.jpg
    - assets/images/moon.jpg
    - assets/images/cat.jpg
    - assets/images/dog.jpg
    - assets/images/hamster.jpg
    - assets/images/HGU.jpg
    - assets/images/goldCrown.png
    - assets/images/silverCrown.png
    - assets/images/bronzeCrown.png
    - assets/images/playButton.png
    - assets/images/playButton2.png
    - assets/images/playButton3.png
    - assets/images/stopButton.png
    - assets/audio/girlVoice.mp3
    - assets/audio/vj.mp3
    - assets/audio/loveRain.mp3
    - assets/audio/yuan.mp3
    - assets/audio/politician.mp3
    - assets/images/testUser.png
    - assets/audio/broadcast/sea.mp3
    - assets/audio/broadcast/piano.mp3
    - assets/images/broadcast/sea.jpg
    - assets/images/broadcast/piano.png
    - assets/images/broadcast/bread.jpg
    - assets/images/broadcast/asmr.jpg
    - assets/images/broadcast/food.jpg
    - assets/images/broadcast/gs.png
    - assets/images/broadcast/talk.jpg
    - assets/images/groupcall/apart.jpg
    - assets/images/groupcall/black.jpg
    - assets/images/groupcall/church.jpg
    - assets/images/groupcall/drama.jpg
    - assets/images/groupcall/english.jpg
    - assets/images/groupcall/talk.jpg
    - assets/images/groupcall/voice.jpg
    - assets/images/groupcall/fish.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Baloo Bhai
      fonts:
        - asset: fonts/BalooBhai-Regular.ttf
    - family: Noto Sans CJK kr-bold
      fonts:
        - asset: fonts/NotoSansCJKkr-Bold.ttf
    - family: Noto Sans CJK kr-regular
      fonts:
        - asset: fonts/NotoSansCJKkr-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages