import 'package:flutter/material.dart';

const PrimaryColorLight = Color(0xFF9FB792);
const OnPrimaryLight = Color(0xFFFFFFFF);
const PrimaryVariantDeepLight = Color(0xFF618051);
const PrimaryVariantLight = Color(0xFFC1E1B0);
const SecondaryLight = Color(0xFFF1CA66);
const SecondaryVariantLight = Color(0xFF21252A);
const OnSecondaryLight = Color(0xFFFFFFFF);
// const BackgroundLight = Color(0xFFFFFFFF);
const BackgroundLight = Color(0xFFFFE8DC);
// const OnBackgroundLight = Color(0xFF4E4E4E);
const OnBackgroundLight = Color(0xFF4A4A4A);
const SurfaceLight = Color(0xFFFFFFFF);
const OnSurfaceLight = Color(0xF434343);
const ErrorLight = Color(0xFFB00020);
const OnErrorLight = Color(0xFFFFFFFF);

const PrimaryColorDark = Color(0xFFBE6DFA);
const PrimaryVariantDark = Color(0xFF6F25E6);
const OnPrimaryDark = Color(0xFFFFFFFF);
const SecondaryDark = Color(0xFF61666C);
const SecondaryVariantDark =  Color(0xFFF5F5F5);
const OnSecondaryDark =  Color(0xFF000000);
const BackgroundDark = Color(0xFF121212);
const OnBackgroundDark = Color(0xFFFFFFFF);
const SurfaceDark = Color(0xFF121212);
const OnSurfaceDark = Color(0xFFFFFFFF);
const ErrorDark = Color(0xFFE3676A);
const OnErrorDark = Color(0xFFFFFFFF);
